# Licensed under the Apache License, Version 2.0 (the "License");
"""Run provenance — stamp tcrsift + dependency versions into deliverables.

So a ``selected_clones.csv`` / sequence PDF / QC report on its own records which
tcrsift and which scientific-stack versions produced it. Without this, a
deliverable installed from PyPI is un-reproducible: you can't tell whether it
came from 2.92.0 (the empty-``db_*`` bug) or a fixed build.

The capture is a curated set of the dependencies whose version can plausibly
change results or output — not the full transitive tree.
"""
from __future__ import annotations

import json
import platform
from datetime import datetime, timezone
from pathlib import Path

from .version import __version__

# Curated: the scientific-stack deps a reviewer would want pinned to reproduce a
# deliverable. scipy is transitive (via scanpy) but result-relevant, so kept.
_PROVENANCE_PACKAGES = (
    "numpy", "pandas", "scipy", "scanpy", "anndata",
    "matplotlib", "seaborn", "pyensembl", "reportlab",
)


def _pkg_version(name: str) -> str | None:
    """Installed version of ``name``, or None if it isn't importable."""
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version(name)
    except PackageNotFoundError:
        return None
    except Exception:  # never let provenance capture break a run
        return None


def collect_provenance(*, now: datetime | None = None) -> dict:
    """Structured provenance: tcrsift, Python, platform, deps, UTC timestamp.

    ``now`` is injectable so callers/tests can pin the timestamp.
    """
    ts = (now or datetime.now(timezone.utc)).strftime("%Y-%m-%dT%H:%M:%SZ")
    return {
        "tcrsift_version": __version__,
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "generated_utc": ts,
        "dependencies": {p: _pkg_version(p) for p in _PROVENANCE_PACKAGES},
    }


def provenance_oneline(prov: dict | None = None) -> str:
    """Compact single line for a PDF footer."""
    p = prov or collect_provenance()
    deps = ", ".join(f"{k} {v}" for k, v in p["dependencies"].items() if v)
    return (
        f"Generated by tcrsift {p['tcrsift_version']} · Python "
        f"{p['python_version']} · {p['generated_utc']} · {deps}"
    )


def provenance_text(prov: dict | None = None) -> str:
    """Multi-line human-readable block (for the QC text file / sidecar .txt)."""
    p = prov or collect_provenance()
    lines = [
        "Provenance",
        f"  tcrsift   : {p['tcrsift_version']}",
        f"  python    : {p['python_version']}",
        f"  platform  : {p['platform']}",
        f"  generated : {p['generated_utc']} (UTC)",
        "  dependencies:",
    ]
    for k, v in p["dependencies"].items():
        lines.append(f"    {k:<11}: {v or '(not installed)'}")
    return "\n".join(lines)


def write_provenance(out_dir, prov: dict | None = None) -> dict:
    """Write ``provenance.json`` + ``provenance.txt`` into ``out_dir``.

    Returns the provenance dict so a caller can reuse it (e.g. to also stamp the
    PDF footer / a CSV column) without re-collecting.
    """
    p = prov or collect_provenance()
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "provenance.json").write_text(json.dumps(p, indent=2) + "\n")
    (out_dir / "provenance.txt").write_text(provenance_text(p) + "\n")
    return p
