# Licensed under the Apache License, Version 2.0 (the "License");
"""Provenance capture (#provenance): tcrsift + dep versions stamped into outputs."""
import json
from datetime import datetime, timezone

from tcrsift.provenance import (
    collect_provenance,
    provenance_oneline,
    provenance_text,
    write_provenance,
)
from tcrsift.version import __version__


def test_collect_provenance_structure():
    p = collect_provenance(now=datetime(2026, 1, 2, 3, 4, 5, tzinfo=timezone.utc))
    assert p["tcrsift_version"] == __version__
    assert p["generated_utc"] == "2026-01-02T03:04:05Z"
    assert p["python_version"] and p["platform"]
    # core deps present in the test env resolve to real versions
    assert p["dependencies"]["numpy"] and p["dependencies"]["pandas"]
    assert "scanpy" in p["dependencies"] and "anndata" in p["dependencies"]


def test_collect_provenance_handles_absent_package(monkeypatch):
    # A dep that isn't installed resolves to None, not a crash.
    import tcrsift.provenance as prov

    monkeypatch.setattr(prov, "_PROVENANCE_PACKAGES", ("numpy", "definitely-not-a-real-pkg"))
    p = prov.collect_provenance()
    assert p["dependencies"]["numpy"]
    assert p["dependencies"]["definitely-not-a-real-pkg"] is None


def test_provenance_text_and_oneline():
    p = collect_provenance()
    text = provenance_text(p)
    assert "Provenance" in text and __version__ in text and "numpy" in text
    one = provenance_oneline(p)
    assert one.startswith("Generated by tcrsift") and __version__ in one


def test_write_provenance_emits_json_and_txt(tmp_path):
    p = write_provenance(tmp_path)
    assert (tmp_path / "provenance.json").exists()
    assert (tmp_path / "provenance.txt").exists()
    loaded = json.loads((tmp_path / "provenance.json").read_text())
    assert loaded["tcrsift_version"] == __version__ == p["tcrsift_version"]
    assert "dependencies" in loaded
